#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := https
BUILD_DIR_BASE := build3

IDF_PATH = /home/danny/src/github/esp32/esp-idf-v3.3.5
# IDF_PATH = /home/danny/src/github/esp32/esp-idf-v4.2.1

include $(IDF_PATH)/make/project.mk

