#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := https

IDF_PATH = /home/danny/src/github/esp32/esp-idf-v3.3.5

include $(IDF_PATH)/make/project.mk

